<a href="https://colab.research.google.com/github/i-mugford/colab-notebooks/blob/master/film_box_office_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import re
from datetime import timedelta, date, datetime
from dateutil.relativedelta import relativedelta, FR

In [228]:
from google.colab import drive 
drive.mount('/content/gdrive')
df=pd.read_csv('gdrive/My Drive/box-office.csv')
df

Mounted at /content/gdrive

     Unnamed: 0                                    movie  ... weeks        date
0             0   Star-Wars-The-Rise-of-Skywalker-(2019)  ...     3  2020-01-03
1             1                   Jumanji-The-Next-Level  ...     4  2020-01-03
2             2                      Little-Women-(2019)  ...     3  2020-01-03
3             3                         Frozen-II-(2019)  ...     7  2020-01-03
4             4                        Grudge-The-(2020)  ...     1  2020-01-03
..          ...                                      ...  ...   ...         ...
858         858                             Wretched-The  ...     5  2020-05-29
859         859                        Strike-(UK)(2019)  ...    10  2020-05-29
860         860  Circles-The-Restorative-Justice-Project  ...     3  2020-05-29
861         861                  Trip-to-Greece-The-(UK)  ...     2  2020-05-29
862         862                 How-to-Build-a-Girl-(UK)  ...     4  2020-05-29

[863 rows x 7 columns]

In [0]:
unique_films_source = df.movie.unique()

In [0]:
new_unique_films = [x.replace('-',' ') for x in unique_films_source]
unique_films = [re.sub('( \(.*\))', '', x) for x in new_unique_films]

In [0]:
import json

In [0]:
movie_details = []
for i in range(0,len(unique_films) - 1):
  url = f'''http://www.omdbapi.com/?t={unique_films[i]}&apikey={apikey}'''
  movie_info = requests.get(url).text 
  if movie_info != '{"Response":"False","Error":"Movie not found!"}':
    info = json.loads(movie_info)
    movie_details.append({"movie":unique_films_source[i],"title":info['Title'],'year':info['Year'],'rating':info['Rated'],'runtime':info['Runtime'],'genre':info['Genre'],'director':info['Director'],'writer':info['Writer'],'actors':info['Actors'],'country':info['Country']})
  
  movie_details_df = pd.DataFrame(data=movie_details)

In [226]:
movie_details_df.head()

                                    movie  ... country
0  Star-Wars-The-Rise-of-Skywalker-(2019)  ...     USA
1                  Jumanji-The-Next-Level  ...     USA
2                     Little-Women-(2019)  ...     USA
3                        Frozen-II-(2019)  ...     USA
4                Spies-in-Disguise-(2019)  ...     USA

[5 rows x 10 columns]

In [225]:
combined_movie_data = pd.merge(left=df, right=movie_details_df, how='inner', left_on='movie', right_on='movie')
combined_movie_data.head()

                                    movie  ... country
0  Star-Wars-The-Rise-of-Skywalker-(2019)  ...     USA
1  Star-Wars-The-Rise-of-Skywalker-(2019)  ...     USA
2  Star-Wars-The-Rise-of-Skywalker-(2019)  ...     USA
3  Star-Wars-The-Rise-of-Skywalker-(2019)  ...     USA
4  Star-Wars-The-Rise-of-Skywalker-(2019)  ...     USA

[5 rows x 15 columns]